/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@ionic/core';
import 'ionicons';


export namespace Components {

  interface AppFontDetail {
    'id': string;
  }
  interface AppFontDetailAttributes extends StencilHTMLAttributes {
    'id'?: string;
  }

  interface AppFont {
    'id': string;
  }
  interface AppFontAttributes extends StencilHTMLAttributes {
    'id'?: string;
  }

  interface AppHome {}
  interface AppHomeAttributes extends StencilHTMLAttributes {}

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}

  interface HighlightCodeLine {
    'lines'?: string;
  }
  interface HighlightCodeLineAttributes extends StencilHTMLAttributes {
    'lines'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AppFontDetail': Components.AppFontDetail;
    'AppFont': Components.AppFont;
    'AppHome': Components.AppHome;
    'AppRoot': Components.AppRoot;
    'HighlightCodeLine': Components.HighlightCodeLine;
  }

  interface StencilIntrinsicElements {
    'app-font-detail': Components.AppFontDetailAttributes;
    'app-font': Components.AppFontAttributes;
    'app-home': Components.AppHomeAttributes;
    'app-root': Components.AppRootAttributes;
    'highlight-code-line': Components.HighlightCodeLineAttributes;
  }


  interface HTMLAppFontDetailElement extends Components.AppFontDetail, HTMLStencilElement {}
  var HTMLAppFontDetailElement: {
    prototype: HTMLAppFontDetailElement;
    new (): HTMLAppFontDetailElement;
  };

  interface HTMLAppFontElement extends Components.AppFont, HTMLStencilElement {}
  var HTMLAppFontElement: {
    prototype: HTMLAppFontElement;
    new (): HTMLAppFontElement;
  };

  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLHighlightCodeLineElement extends Components.HighlightCodeLine, HTMLStencilElement {}
  var HTMLHighlightCodeLineElement: {
    prototype: HTMLHighlightCodeLineElement;
    new (): HTMLHighlightCodeLineElement;
  };

  interface HTMLElementTagNameMap {
    'app-font-detail': HTMLAppFontDetailElement
    'app-font': HTMLAppFontElement
    'app-home': HTMLAppHomeElement
    'app-root': HTMLAppRootElement
    'highlight-code-line': HTMLHighlightCodeLineElement
  }

  interface ElementTagNameMap {
    'app-font-detail': HTMLAppFontDetailElement;
    'app-font': HTMLAppFontElement;
    'app-home': HTMLAppHomeElement;
    'app-root': HTMLAppRootElement;
    'highlight-code-line': HTMLHighlightCodeLineElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
