/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AppFont {
    'id': string;
  }
  interface AppFontDetail {
    'id': string;
  }
  interface AppHome {}
  interface AppRoot {}
  interface HighlightCodeLine {
    'lines'?: string;
  }
}

declare global {


  interface HTMLAppFontElement extends Components.AppFont, HTMLStencilElement {}
  var HTMLAppFontElement: {
    prototype: HTMLAppFontElement;
    new (): HTMLAppFontElement;
  };

  interface HTMLAppFontDetailElement extends Components.AppFontDetail, HTMLStencilElement {}
  var HTMLAppFontDetailElement: {
    prototype: HTMLAppFontDetailElement;
    new (): HTMLAppFontDetailElement;
  };

  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLHighlightCodeLineElement extends Components.HighlightCodeLine, HTMLStencilElement {}
  var HTMLHighlightCodeLineElement: {
    prototype: HTMLHighlightCodeLineElement;
    new (): HTMLHighlightCodeLineElement;
  };
  interface HTMLElementTagNameMap {
    'app-font': HTMLAppFontElement;
    'app-font-detail': HTMLAppFontDetailElement;
    'app-home': HTMLAppHomeElement;
    'app-root': HTMLAppRootElement;
    'highlight-code-line': HTMLHighlightCodeLineElement;
  }
}

declare namespace LocalJSX {
  interface AppFont {
    'id'?: string;
  }
  interface AppFontDetail {
    'id'?: string;
  }
  interface AppHome {}
  interface AppRoot {}
  interface HighlightCodeLine {
    'lines'?: string;
  }

  interface IntrinsicElements {
    'app-font': AppFont;
    'app-font-detail': AppFontDetail;
    'app-home': AppHome;
    'app-root': AppRoot;
    'highlight-code-line': HighlightCodeLine;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'app-font': LocalJSX.AppFont & JSXBase.HTMLAttributes<HTMLAppFontElement>;
      'app-font-detail': LocalJSX.AppFontDetail & JSXBase.HTMLAttributes<HTMLAppFontDetailElement>;
      'app-home': LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
      'app-root': LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
      'highlight-code-line': LocalJSX.HighlightCodeLine & JSXBase.HTMLAttributes<HTMLHighlightCodeLineElement>;
    }
  }
}


